# Generated by Django 3.2.7 on 2021-10-08 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0003_alter_customer_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='is_customer',
            new_name='iscustomer',
        ),
    ]
