# Generated by Django 3.2.7 on 2021-10-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0004_rename_is_customer_contact_iscustomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='planseguro',
            name='company',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
