# Generated by Django 3.2.9 on 2021-11-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0005_planseguro_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planseguro',
            name='coverage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='planseguro',
            name='deducible',
            field=models.IntegerField(),
        ),
    ]
