# Generated by Django 3.2.9 on 2021-11-22 15:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0006_auto_20211117_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\d{1,15}$')]),
        ),
    ]
