# Generated by Django 3.2.9 on 2021-11-22 15:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0007_alter_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.CharField(blank=True, max_length=3, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,3}$')]),
        ),
    ]
